/*
 *  ap_csm.r -- resources for the AirPort Extreme Control Strip module.
 *
 *  ⚠⚠ A 'cfrg' FRAGMENT WITH THE PEF IN THE DATA FORK, NOT AN 'sdev' RESOURCE. Both load and run, but
 *  the Control Strip will not let you option-drag a copy of an 'sdev'-resource module out of the strip;
 *  every stock module is a cfrg fragment. RE'd from the stock modules (os9_control_strip_module note,
 *  proven by the Bluetooth and CPU-temp modules). The file is Finder type 'sdev' and carries NO 'sdev'
 *  resource; scripts/patch-pef-main.py points the fragment's main at ControlStripModule.
 */
#include "CodeFragments.r"

resource 'cfrg' (0) {
    {
        kPowerPCCFragArch, kIsCompleteCFrag, kNoVersionNum, kNoVersionNum,
        kDefaultStackSize, kNoAppSubFolder,
        kImportLibraryCFrag, kDataForkCFragLocator, kZeroOffset, kCFragGoesToEOF,
        "AirPort Extreme"
    }
};

/* 'vers' defined inline: this Rez set's SysTypes.r does not carry it. Safe in a normal file's fork --
 * the "vers(1) breaks boot" hazard is ROM-only. ⚠ BOTH strings carry the version; CMake checks. */
type 'vers' {
    hex byte; hex byte; hex byte; hex byte; integer; pstring; pstring;
};
resource 'vers' (1) {
    0x01, 0xA0, 0x80, 0x00,
    0,
    "1.10",
    "1.10 - AirPort Extreme signal, status, on/off, and choosing a network (open or WPA2) from the strip"
};

/* ---- Finder bundle (kHasBundle is set post-Rez by scripts/set-custom-icon.py --bundle; without it
 * the strip will not let a copy be dragged out). Owner 'APXs'.
 * ★ The icon is the user's "AirPort Extreme Strip" family (ap_csm_icon.r, generated by art/make-art.py),
 * carried TWICE: at -16455 with kHasCustomIcon, which the Finder shows straight from this file with no
 * desktop-database step, and at 128 for the bundle's ICN# entry below. ⚠ The two must travel together: a
 * BNDL naming an icon family the file does not carry, or the custom-icon flag without one, renders a
 * BLANK icon that reads as corrupt (a bug this project shipped once). */
data 'APXs' (0) {
    "1.10, github.com/UnexpectedBomb"
};

/* FREF: file type 'sdev', local icon ID 0, empty name. */
data 'FREF' (128) {
    $"7364 6576 0000 00"
};

/* BNDL: owner 'APXs', owner ID 0, TWO types (count-1 = 1):
 *   'ICN#', one entry: local 0 -> ICN# 128 (the family in ap_csm_icon.r)
 *   'FREF', one entry: local 0 -> FREF 128 */
data 'BNDL' (128) {
    $"4150 5873 0000 0001"
    $"4943 4E23 0000 0000 0080"
    $"4652 4546 0000 0000 0080"
};
