/* airport_stage3b.r -- resources for the Stage 3b microcode-upload probe.
 *
 * ⚠ The firmware itself is NOT here. It lives in firmware_blobs.r, which is generated by
 * embed-fw.sh from the local firmware/v3/ blobs and is gitignored -- it contains proprietary
 * Broadcom microcode verbatim. See firmware/README.md.
 *
 * The partition is larger than 3a's because the app's resource fork now carries ~24 KB of
 * microcode that the Resource Manager will load into the heap when GetResource'd. */
#include "Processes.r"
#include "Types.r"

resource 'SIZE' (-1) {
    reserved, acceptSuspendResumeEvents, reserved, canBackground,
    multiFinderAware, backgroundAndForeground, dontGetFrontClicks,
    ignoreChildDiedEvents, is32BitCompatible, isHighLevelEventAware,
    onlyLocalHLEvents, notStationeryAware, dontUseTextEditServices,
    notDisplayManagerAware, reserved, reserved,
    700 * 1024, 600 * 1024
};

resource 'vers' (1, "AirPortStage3b") {
    0x01, 0x00, development, 0x00, verUS,
    "d2", "d2 AirPort Stage 3b: upload ucode5 + pcm5 and start the PSM (needs a fresh boot)"
};
