/* ap_otmodl.r -- the CFM fragment declaration for the NATIVE OTModl$AirPortBCM DLPI module.
 *
 * A SHARED LIBRARY ('shlb'), resolved BY FRAGMENT NAME. Open Transport loads a STREAMS module by
 * building "OTModl$" + OTPortRecord.fModuleName and calling GetSharedLibrary on it, then
 * FindSymbol("GetOTInstallInfo"). So the fragment must be named exactly "OTModl$AirPortBCM", which
 * is what the generated 'cfrg' below declares. Our boot vehicle names the port's module
 * "AirPortBCM" via OTRegisterPort; OT does the "OTModl$" + name join.
 *
 * ⚠ NO patch-pef-main.py step and NO 'ndrv' member: this is a STREAMS module entered through
 *   GetOTInstallInfo, not a Device Manager native driver. `main` is irrelevant here. That is the
 *   whole difference from ap_shim.r, whose fragment also answers to a Device-Manager reader.
 *
 * ⚠ Single-member cfrg, so unlike ap_shim_cfrg.r this shape is expressible in Rez -- but it is
 *   still generated by make-cfrg.py, to keep ONE proven cfrg byte-layout in the project. The
 *   Rez #include dependency is declared in CMakeLists (Rez includes are invisible to CMake).
 */
#include "CodeFragmentTypes.r"

#include "ap_otmodl_cfrg.r"

/* ⚠ STANDING (user, 2026-09-27): BOTH shipped extensions must carry a 'vers' so Get Info shows the
 * installed version. The Startup already has one (ap_init.r); this adds it to the OTModl module, whose
 * absence let a stale k175 module masquerade as k176. Keep this build number in lockstep with
 * AP_OTMODL_BUILD in ap_otmodl.c on every build. */
#include "Types.r"

resource 'vers' (1, locked) {
    0x01, 0x87, beta, 0x00, verUS,
    "1.0b187",
    "AirPort Extreme OTModl 1.0b187 (native OTModl$AirPortBCM DLPI module; OTMODL build 187)"
};

resource 'vers' (2, locked) {
    0x01, 0x87, beta, 0x00, verUS,
    "1.0b187",
    "AirPort Extreme OTModl 1.0b187 (native OTModl$AirPortBCM DLPI module; OTMODL build 187)"
};
