/* GENERATED BY make-cfrg.py -- do not edit. Single-member cfrg for a native
 * CFM fragment resolved by name (here: OTModl$AirPortBCM). */
data 'cfrg' (0) {
    $"0000 0000 0000 0000 0000 0001 0000 0000"
    $"0000 0000 0000 0000 0000 0000 0000 0001"
    $"7077 7063 0000 0000 0000 0000 0000 0000"
    $"0000 0000 0000 0001 0000 0000 0000 0000"
    $"0000 0000 0000 0000 003C 114F 544D 6F64"
    $"6C24 4169 7250 6F72 7442 434D"
};
