#!/bin/bash
# embed-fw.sh -- hex-encode the BCM4306 v3 firmware blobs into a Rez 'data' resource file so the
# Stage 3b app can GetResource them and upload them to the chip.
#
# Same technique as esata-sil3512/probe/embed-pef.sh, and the same technique Apple's own OS 9
# AirPort Driver uses: it carries Lucent Hermes firmware as 'Fdat' resources and loads them through
# the Resource Manager at task level. We are copying a shipping precedent, not inventing one.
#
# ⚠ THE OUTPUT IS GITIGNORED. It contains proprietary Broadcom microcode verbatim; committing it
# would be redistribution by another name. See firmware/README.md for the fetch and the hash.
#
# The blobs must already be present. Fetch them with:
#   curl -sSL -o v3.tbz https://leaf.dragonflybsd.org/~sephe/bwi/v3.tbz && tar -xjf v3.tbz
set -eu

# ⚠ DEFAULTS TO v4 SINCE 2026-09-19. The v3 blobs (ucode rev 295) are what Stage 5-4 was stuck on:
# b43 rejects any firmware with rev <= 0x128 outright, and the whole port is b43-derived, so the
# v3 microcode was reading our 106-byte b43_txhdr as its own 82-byte layout -- null PLCP, null
# destination address. See FEASIBILITY.md, "THE FIRMWARE AND THE DRIVER CODE ARE FROM MUTUALLY
# EXCLUSIVE GENERATIONS". Pass ../firmware/v3 explicitly if you ever need the old set back.
FWDIR="${1:-../firmware/v4}"
OUT="${2:-firmware_blobs.r}"
GEN="$(basename "$FWDIR")"

emit_one() {   # emit_one <file> <restype> <resid> <description>
    local f="$1" t="$2" id="$3" desc="$4"
    [ -f "$f" ] || { echo "embed-fw: MISSING $f" >&2; echo "embed-fw: fetch the firmware first -- see firmware/README.md" >&2; exit 1; }
    echo "/* $(basename "$f") -- $(wc -c < "$f" | tr -d ' ') bytes */"
    echo "data '$t' ($id, \"$desc\") {"
    xxd -p -c 16 "$f" | sed 's/^/    $"/; s/$/"/'
    echo "};"
    echo
}

{
  echo "/* AUTO-GENERATED by embed-fw.sh -- DO NOT EDIT, DO NOT COMMIT."
  echo " * Proprietary Broadcom microcode, $GEN generation, for BCM4306 802.11 core rev 5."
  echo " * Cut from $FWDIR"
  echo " * Generated $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo " *"
  echo " * Each blob keeps its 8-byte header: {u8 type; u8 ver; u8 pad[2]; be32 size}. bwi's"
  echo " * struct bwi_fwhdr and b43's struct b43_fw_header are byte-for-byte identical, so the"
  echo " * same loader reads either generation -- only the CONTENTS differ."
  echo " * The app checks that header before uploading a single word, so a truncated or wrong-file"
  echo " * resource is caught on the host rather than halfway into the chip's microcode RAM."
  echo " */"
  echo
  emit_one "$FWDIR/ucode5.fw"          BCMu 128 "ucode5 (802.11 core rev 5)"
  emit_one "$FWDIR/pcm5.fw"            BCMp 128 "pcm5 (crypto engine microcode)"
  emit_one "$FWDIR/b0g0initvals5.fw"   BCMi 128 "b0g0initvals5 (G-PHY init values)"
  emit_one "$FWDIR/b0g0bsinitvals5.fw" BCMi 129 "b0g0bsinitvals5 (G-PHY band-switch init values)"
} > "$OUT.tmp"

mv "$OUT.tmp" "$OUT"
echo "embed-fw: wrote $OUT ($(wc -c < "$OUT" | tr -d ' ') bytes of Rez)"

# ── Stage 8-2c: the same blobs again, as C arrays, for the DRIVER ─────────────────────────────
#
# ⚠ WHY THE DRIVER CANNOT USE THE RESOURCES ABOVE. The application reads them with
#   GetResource('BCMu',128), which works because an application's own resource fork is open. A CFM
#   SHARED LIBRARY's resource fork is not in the resource chain, so the shim would have to find its
#   own file and FSpOpenResFile it -- which needs the FSSpec that only a CFM init routine supplies.
#   MakePEF in this toolchain exposes no way to declare one, so that route starts with an unknown.
#
# ⚠ AND THE HONEST ALTERNATIVE WAS NOT "just call GetResource anyway". That would have read the
#   APPLICATION'S resources from inside the driver: it would have worked today, looked like
#   independence, and silently kept the coupling that the whole migration exists to remove.
#
# So the driver gets its own copy, compiled in. The cost is ~26 KB in the code fragment and a
# second place the blobs live; the benefit is no File Manager, no FSSpec, no resource chain, and a
# driver that is genuinely self-sufficient. Apple's own AirPort driver uses resources ('Fdat') --
# that remains the nicer end state and a packaging change, not a correctness one.
#
# ⚠ GITIGNORED, exactly like the Rez output, and for exactly the same reason: proprietary Broadcom
#   microcode. Committing it would be redistribution by another name.
COUT="${OUT%.r}_c.h"
emit_c_one() {   # emit_c_one <file> <symbol> <description>
    local f="$1" sym="$2" desc="$3"
    [ -f "$f" ] || { echo "embed-fw: MISSING $f" >&2; exit 1; }
    echo "/* $(basename "$f") -- $desc -- $(wc -c < "$f" | tr -d ' ') bytes */"
    echo "static const unsigned char ${sym}[] = {"
    xxd -i < "$f" | sed 's/^/    /'
    echo "};"
    echo "#define ${sym}_LEN ((unsigned long)sizeof(${sym}))"
    echo
}
{
  echo "/* AUTO-GENERATED by embed-fw.sh -- DO NOT EDIT, DO NOT COMMIT."
  echo " * Proprietary Broadcom microcode, $GEN generation, for BCM4306 802.11 core rev 5."
  echo " * The DRIVER's copy: see the long note in embed-fw.sh for why the shim cannot read the"
  echo " * application's resources and must carry its own."
  echo " * Each blob keeps its 8-byte header {u8 type; u8 ver; u8 pad[2]; be32 size}, so the same"
  echo " * validation the app performs runs unchanged on these."
  echo " * Generated $(date -u +%Y-%m-%dT%H:%M:%SZ) from $FWDIR"
  echo " */"
  echo "#ifndef AP_FW_BLOBS_C_H"
  echo "#define AP_FW_BLOBS_C_H"
  echo
  emit_c_one "$FWDIR/ucode5.fw"          kApFwUcode  "ucode5 (802.11 core rev 5)"
  emit_c_one "$FWDIR/pcm5.fw"            kApFwPcm    "pcm5 (crypto engine microcode)"
  emit_c_one "$FWDIR/b0g0initvals5.fw"   kApFwIv     "b0g0initvals5 (G-PHY init values)"
  emit_c_one "$FWDIR/b0g0bsinitvals5.fw" kApFwBsIv   "b0g0bsinitvals5 (band-switch init values)"
  echo "#endif"
} > "$COUT.tmp"
mv "$COUT.tmp" "$COUT"
echo "embed-fw: wrote $COUT ($(wc -c < "$COUT" | tr -d ' ') bytes of C) for the driver"
