#!/usr/bin/env python3
"""icons-to-rez.py -- turn a Mac icon family resource fork into Rez source.

WHY THIS EXISTS. The AirPort Extreme extension's icon family arrived as a Mac file whose data fork
is empty and whose resource fork holds seven icon resources at ID -16455 ("Item Icon"), which is
the custom-file-icon convention. To make every future build carry that icon we need the resources
in the build itself, not grafted on afterwards by hand -- a manual post-build step is a step that
gets forgotten, and the icon would silently vanish on some later increment.

Retro68 ships Rez but NOT DeRez, so there is no stock way to go from a resource fork back to Rez
source. This does that, emitting `data` statements which Rez accepts for any type.

⚠ READ-ONLY ON THE SOURCE, and it writes to stdout. It never modifies the file it reads, and the
  caller redirects into a .r that is then committed -- so the share is needed once, not at every
  build. That is the whole point: after this runs, the repository is self-contained.

Usage:  ./icons-to-rez.py "/path/to/icon file" > ap_shim_icons.r
"""
import sys, struct

def resources(raw):
    """Yield (type, id, name, attrs, data) from a classic resource fork."""
    if len(raw) < 16:
        return
    data_off, map_off, _data_len, _map_len = struct.unpack('>IIII', raw[:16])
    type_list = map_off + struct.unpack('>H', raw[map_off+24:map_off+26])[0]
    name_list = map_off + struct.unpack('>H', raw[map_off+26:map_off+28])[0]
    ntypes = struct.unpack('>h', raw[type_list:type_list+2])[0] + 1
    for i in range(ntypes):
        e = type_list + 2 + i*8
        rtype = raw[e:e+4].decode('mac-roman')
        count = struct.unpack('>H', raw[e+4:e+6])[0] + 1
        ref   = type_list + struct.unpack('>H', raw[e+6:e+8])[0]
        for j in range(count):
            r = ref + j*12
            rid   = struct.unpack('>h', raw[r:r+2])[0]
            noff  = struct.unpack('>h', raw[r+2:r+4])[0]
            packed= struct.unpack('>I', raw[r+4:r+8])[0]
            attrs = (packed >> 24) & 0xFF
            doff  = packed & 0xFFFFFF
            dlen  = struct.unpack('>I', raw[data_off+doff:data_off+doff+4])[0]
            body  = raw[data_off+doff+4 : data_off+doff+4+dlen]
            name  = ''
            if noff != -1:
                ln = raw[name_list+noff]
                name = raw[name_list+noff+1 : name_list+noff+1+ln].decode('mac-roman')
            yield rtype, rid, name, attrs, body

# Rez attribute keywords, in the order Rez expects them.
ATTRS = [(0x40,'sysheap'), (0x20,'purgeable'), (0x10,'locked'),
         (0x08,'protected'), (0x04,'preload')]

def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    raw = open(sys.argv[1] + '/..namedfork/rsrc', 'rb').read()
    out = sys.stdout.write
    out('/* ap_shim_icons.r -- GENERATED by icons-to-rez.py. Do not hand-edit.\n'
        ' *\n'
        ' * The AirPort Extreme extension icon family, as supplied. ID -16455 with the name\n'
        ' * "Item Icon" is the custom-file-icon convention: a file carrying these in its resource\n'
        ' * fork, with the Finder\'s custom-icon flag set, shows this icon instead of the generic\n'
        ' * one for its type.\n'
        ' *\n'
        ' * ⚠ THE FLAG IS NOT IN THIS FILE. Rez writes the resources; the kHasCustomIcon bit is a\n'
        ' *   Finder attribute on the file, set by `SetFile -a C` in package-probe.sh. Both halves\n'
        ' *   are required -- resources alone show nothing, and the flag alone shows a blank icon.\n'
        ' */\n\n')
    n = 0
    for rtype, rid, name, attrs, body in resources(raw):
        kw = [k for bit, k in ATTRS if attrs & bit]
        head = "data '%s' (%d" % (rtype, rid)
        if name:
            head += ', "%s"' % name
        for k in kw:
            head += ', ' + k
        head += ') {\n'
        out(head)
        for off in range(0, len(body), 16):
            chunk = body[off:off+16]
            hexed = ' '.join(chunk[i:i+2].hex().upper() for i in range(0, len(chunk), 2))
            out('    $"%s"\n' % hexed)
        out('};\n\n')
        n += 1
    sys.stderr.write('icons-to-rez: emitted %d resource(s)\n' % n)

main()
