#!/usr/bin/env python3
"""make-cfrg.py -- emit a MULTI-MEMBER 'cfrg' as a Rez data blob.

★ WHY THIS EXISTS. Our fragment has to answer to TWO names at once:

    "AirPortShim"   what the test application asks CFM for by name. k100 proved how load-bearing
                    this is -- typing the FILE 'ndrv' broke GetSharedLibrary with -2804.
    "pci80211"      what OPEN TRANSPORT looks for. OT is the I/O expert for networking and it
                    finds a PCI network driver as a CFM fragment NAMED AFTER THE NAME REGISTRY
                    NODE. Our node is "pci80211" (measured at k98).

⚠ AN EARLIER VERSION OF THIS FILE HAD THE REASON WRONG. It said Apple declares OTModl$radio
  twice, "pwpc AND 'ndrv'", and the second member here carried architecture 'ndrv' to match.
  Re-reading the actual resource says otherwise -- `AirPort Driver` has THREE members and every
  one of them is pwpc / kImportLibraryCFrag:

      "WirelessAPI"      pwpc  ImportLibrary  off=0      len=73284
      "OTPortCfg$radio"  pwpc  ImportLibrary  off=73296  len=1341
      "OTModl$radio"     pwpc  ImportLibrary  off=74640  len=65261

  There is no 'ndrv' architecture in it at all. k101 tested a shape that does not exist.

★ THE TWO-NAMES-ONE-PEF IDIOM IS APPLE'S OWN, and `AirPort AP Support` is the proof -- two
  members, "OTModl$Proxym" and "OTModl$Proxy", BOTH at offset 0 with length toEOF. The same PEF,
  described twice, for two readers. That is exactly what we emit below.

⛔ AND RETRO68'S REZ CANNOT EXPRESS IT. CodeFragments.r's template rejects a second array member
  with "extra value specified" -- verified with a minimal two-member test where BOTH members were
  identical PowerPC entries, so it is the template, not the content. Rather than fight Rez, emit
  the resource as bytes.

The layout is from CodeFragments.r's own template, and it is confirmed against Apple's driver:
parsing their cfrg with these offsets recovers the three names above with sane usage and locator
values, which a wrong layout would not.

    header   8 longs: reserved, reserved, version=1, reserved x4, memberCount
    member   archType(4) updateLevel(4) currentVersion(4) oldDefVersion(4)
             appStackSize(4) appSubFolderID(2) usage(1) where(1)
             offset(4) length(4) reserved(4) reserved(4) memberSize(2) pstring(name)
             then padded to a 4-byte boundary

Usage:  make-cfrg.py <out.r>                     the shim's 3-member cfrg (default)
        make-cfrg.py <out.r> <FragmentName>     a single-member cfrg (the native OTModl module)

★ THE SINGLE-MEMBER MODE (8-58) is for the native DLPI module OTModl$AirPortBCM. It rides the
  same proven byte layout, one member, so OT resolves "OTModl$AirPortBCM" by name after
  OTRegisterPort names it in OTPortRecord.fModuleName ("AirPortBCM" -> "OTModl$" + it). No scanner
  member and no node-named member: we self-register the port rather than wait to be discovered,
  which is what the k100-k103 discovery route never achieved.
"""
import struct, sys

kImportLibraryCFrag   = 0
kDataForkCFragLocator = 1
kIsCompleteCFrag      = 0
kZeroOffset           = 0
kCFragGoesToEOF       = 0

def member(arch, name, usage=kImportLibraryCFrag, where=kDataForkCFragLocator):
    nm = name.encode('mac-roman')
    body = (struct.pack('>4s', arch.encode('mac-roman'))
            + struct.pack('>i', kIsCompleteCFrag)
            + struct.pack('>I', 0)                 # currentVersion  kNoVersionNum
            + struct.pack('>I', 0)                 # oldDefVersion   kNoVersionNum
            + struct.pack('>i', 0)                 # appStackSize    kDefaultStackSize
            + struct.pack('>h', 0)                 # appSubFolderID  kNoAppSubFolder
            + bytes([usage, where])
            + struct.pack('>i', kZeroOffset)
            + struct.pack('>i', kCFragGoesToEOF)
            + struct.pack('>i', 0)                 # reserved
            + struct.pack('>i', 0))                # reserved
    size = len(body) + 2 + 1 + len(nm)             # + memberSize field + pstring
    pad  = (-size) % 4
    size += pad
    return body + struct.pack('>H', size) + bytes([len(nm)]) + nm + b'\0' * pad

def build(members):
    out = struct.pack('>7i', 0, 0, 1, 0, 0, 0, 0) + struct.pack('>i', len(members))
    for m in members:
        out += m
    return out

if __name__ == '__main__':
    # 8-58: single-member mode -- one pwpc ImportLibrary member named on the command line, over the
    # whole PEF. Used for OTModl$AirPortBCM (the native module) and any OTPortCfg$ helper later.
    if len(sys.argv) > 2:
        name = sys.argv[2]
        blob = build([member('pwpc', name)])
        hexs = blob.hex().upper()
        lines = [hexs[i:i+32] for i in range(0, len(hexs), 32)]
        with open(sys.argv[1], 'w') as f:
            f.write("/* GENERATED BY make-cfrg.py -- do not edit. Single-member cfrg for a native\n"
                    " * CFM fragment resolved by name (here: %s). */\n" % name)
            f.write("data 'cfrg' (0) {\n")
            for l in lines:
                f.write('    $"%s"\n' % " ".join(l[i:i+4] for i in range(0, len(l), 4)))
            f.write("};\n")
        print("make-cfrg: single member %r, %d bytes -> %s" % (name, len(blob), sys.argv[1]))
        sys.exit(0)

    blob = build([
        # [1] the shared library. CFM registers this BY NAME and everything else depends on it.
        member('pwpc', 'AirPortShim'),
        # [2] the SAME PEF, described again under the NAME REGISTRY NODE NAME, which is the name
        #     Open Transport looks a PCI network driver up by. Same offset, same length, same
        #     architecture -- only the name differs. Keep this string equal to
        #     AP_NDRV_NODE_NAME in ap_ndrv.h and to TheDriverDescription.nameInfoStr; Apple's
        #     three descriptors all carry their own fragment name in that field.
        member('pwpc', 'pci80211'),
        # [3] ★★★ THE PORT SCANNER, and this is the member k103 is actually testing.
        #     OpenTransport.h:245 defines kOTKernelPrefix "OTKrnl$"; OpenTransportKernel.h:1361
        #     says a port scanner must carry that prefix and export "OTScanPorts". Apple's is
        #     "OTKrnl$USBOTPortScanner" in `Apple Enet DLPI Support` -- a free-form suffix, so
        #     OT is matching the PREFIX, not an exact tag.
        #     ⚠ This is how an EXTENSION-delivered Ethernet gets into TCP/IP. The node-named
        #       members above ("pci80211") are the ROM/PCI-discovery route, which is why k102's
        #       live port list shows module "gmac" with no such fragment anywhere on disk.
        member('pwpc', 'OTKrnl$AirPortPortScanner'),
    ])
    hexs = blob.hex().upper()
    lines = [hexs[i:i+32] for i in range(0, len(hexs), 32)]
    with open(sys.argv[1], 'w') as f:
        f.write("/* GENERATED BY make-cfrg.py -- do not edit. See that script for why this is a\n"
                " * byte blob rather than a Rez 'cfrg' template: Retro68's Rez cannot express a\n"
                " * multi-member cfrg, and Apple's driver needs exactly that shape. */\n")
        f.write("data 'cfrg' (0) {\n")
        for l in lines:
            f.write('    $"%s"\n' % " ".join(l[i:i+4] for i in range(0, len(l), 4)))
        f.write("};\n")
    print("make-cfrg: AirPortShim + pci80211 + OTKrnl$AirPortPortScanner, %d bytes -> %s"
          % (len(blob), sys.argv[1]))
