#!/usr/bin/env python3
"""make-airport-driver.py -- assemble the THREE AirPort fragments into one Apple-shaped shlb.

★ 8-82 k188. Apple's `Apple Enet DLPI Support` is a single shlb file: its data fork is three PEFs
concatenated at 16-byte-aligned offsets, and its 'cfrg' declares all three as pwpc ImportLibraries,
with the SCANNER member carrying a typed 'otan' extension whose first string is "OTKrnl$pScnr" --
the tag OT keys on to find a port scanner and call its OTScanPorts. This script produces the same:

    data fork  = OTModl$AirPortBCM || OTPortCfg$AirPortCfgHelper || OTKrnl$AirPortScanner  (16-aligned)
    cfrg       = 3 members; OTModl -> 'shlb' ext "AirPortBCM"; scanner -> 'otan' ext "OTKrnl$pScnr"

The cfrg byte layout is CodeFragments.r's extendedEntry (cfrg_RezTemplateVersion=1), verified field
for field against Apple's own cfrg (magic 0x30EE, extensionCount=1, the four qualifier pstrings).

Usage: make-airport-driver.py <out_cfrg.r> <out_data.bin> <otmodl.pef> <portcfg.pef> <scanner.pef>
"""
import struct, sys

ALIGN = 16   # PEFs sit at 16-byte-aligned offsets in the data fork, as Apple's do

def pstr(s):
    b = s.encode('mac-roman')
    assert len(b) < 256
    return bytes([len(b)]) + b

def extension(libKind, q1, q2, info, intl):
    """extendedEntry extension: int16 magic 0x30EE, int16 size, OSType libKind, 4 pstrings, align 4."""
    payload = struct.pack('>4s', libKind.encode('mac-roman')) + pstr(q1) + pstr(q2) + pstr(info) + pstr(intl)
    size = 2 + 2 + len(payload)          # magic + size + payload
    size += (-size) % 4                  # align the extension to 4
    out = struct.pack('>H', 0x30EE) + struct.pack('>H', size) + payload
    out += b'\x00' * (size - len(out))
    return out

def member(arch, name, offset, length, ext=None):
    """One cfrg member (extendedEntry). memberSize is the whole member length, 4-aligned."""
    fixed = (struct.pack('>4s', arch.encode('mac-roman'))
             + struct.pack('>i', 0)      # updateLevel = kIsCompleteCFrag
             + struct.pack('>I', 0)      # currentVersion = kNoVersionNum
             + struct.pack('>I', 0)      # oldDefVersion  = kNoVersionNum
             + struct.pack('>i', 0)      # appStackSize   = kDefaultStackSize
             + struct.pack('>h', 0)      # appSubFolderID = kNoAppSubFolder
             + bytes([0, 1])             # usage=kImportLibraryCFrag, where=kDataForkCFragLocator
             + struct.pack('>i', offset)
             + struct.pack('>i', length)
             + struct.pack('>i', 0)      # reserved long
             + struct.pack('>h', 0)      # reserved int
             + struct.pack('>H', 1 if ext else 0))   # extensionCount (key integer)
    # memberSize(2) + pstring name, then align long, then the extension, then align long (memberEnd)
    tail = pstr(name)
    body = fixed + b'\x00\x00' + tail            # memberSize placeholder
    body += b'\x00' * ((-len(body)) % 4)         # align long after the name
    if ext:
        body += ext
    body += b'\x00' * ((-len(body)) % 4)         # align long at memberEnd
    ms = len(body)
    return body[:len(fixed)] + struct.pack('>H', ms) + body[len(fixed)+2:]

def build_cfrg(members):
    out = struct.pack('>7i', 0, 0, 1, 0, 0, 0, 0) + struct.pack('>i', len(members))
    for m in members:
        out += b'\x00' * ((-len(out)) % 4)       # each member starts long-aligned (memberStart)
        out += m
    return out

def rez_data(name, blob):
    hexs = blob.hex().upper()
    lines = [hexs[i:i+32] for i in range(0, len(hexs), 32)]
    s = ("/* GENERATED BY make-airport-driver.py -- do not edit. 3-member cfrg for the combined\n"
         " * AirPort driver (OTModl$ + OTPortCfg$ + OTKrnl$ scanner), extendedEntry layout with the\n"
         " * 'otan'/\"OTKrnl$pScnr\" scanner extension. Offsets/lengths match the data fork below. */\n")
    s += "data 'cfrg' (0) {\n"
    for l in lines:
        s += '    $"%s"\n' % " ".join(l[i:i+4] for i in range(0, len(l), 4))
    s += "};\n"
    return s

if __name__ == '__main__':
    out_cfrg, out_data, p_otmodl, p_portcfg, p_scanner = sys.argv[1:6]
    pefs = [(p_otmodl,  'OTModl$AirPortBCM',        ('shlb', 'AirPortBCM', '', '', '')),
            (p_portcfg, 'OTPortCfg$AirPortCfgHelper', None),
            (p_scanner, 'OTKrnl$AirPortScanner',    ('otan', 'OTKrnl$pScnr', '', '', 'AirPort BCM Port Scanner'))]
    data = b''
    members = []
    for path, name, extspec in pefs:
        pef = open(path, 'rb').read()
        data += b'\x00' * ((-len(data)) % ALIGN)   # 16-align this PEF's start
        offset = len(data)
        data += pef
        ext = extension(*extspec) if extspec else None
        members.append(member('pwpc', name, offset, len(pef), ext))
        print("  member %-28s off=%#08x len=%d%s" % (name, offset, len(pef), " +'%s' ext" % extspec[0] if extspec else ""))
    open(out_data, 'wb').write(data)
    open(out_cfrg, 'w').write(rez_data('cfrg', build_cfrg(members)))
    print("make-airport-driver: data fork %d bytes -> %s ; cfrg -> %s" % (len(data), out_data, out_cfrg))
