/*
 *  ap_panel.r -- resources for the AirPort Extreme control panel.
 *
 *  Rez'd AFTER Retro68's RetroPPCAPPL.r template (add_application appends the project's compiled .r
 *  files to the final Rez), so the SIZE below replaces the template's.
 */
#include "Processes.r"
#include "Menus.r"
#include "Dialogs.r"

/* ★ NOT the Retro68 default SIZE, which is cannotBackground and notHighLevelEventAware:
 *   - canBackground: the panel keeps reading the driver while another application is in front, so a
 *     glance at it is current (and so the strip module's "Open AirPort Extreme" finds it up to date);
 *   - acceptSuspendResumeEvents: a resume re-reads the TCP/IP configuration, which the user may just
 *     have changed; needsActivateOnFGSwitch keeps the system sending the activate events that dim the
 *     window when it goes behind;
 *   - isHighLevelEventAware: the Finder quits it at Shut Down with a 'quit' Apple event, which
 *     ap_panel.c answers -- a panel left open must not hold up Shut Down. */
resource 'SIZE' (-1) {
    reserved,
    acceptSuspendResumeEvents,
    reserved,
    canBackground,
    needsActivateOnFGSwitch,
    backgroundAndForeground,
    dontGetFrontClicks,
    ignoreAppDiedEvents,
    is32BitCompatible,
    isHighLevelEventAware,
    onlyLocalHLEvents,
    notStationeryAware,
    dontUseTextEditServices,
    notDisplayManagerAware,
    reserved,
    reserved,
    1024 * 1024,
    1024 * 1024
};

/* 'vers' defined inline, as ../csm/ap_csm.r does. vers(1) is what Get Info and Apple System Profiler read
 * (bluetooth/cpanel lost ASP's "Version" column without it); vers(2) is the same, for the Finder's
 * package line. Safe in an application: the "vers(1) breaks boot" hazard is ROM-only.
 * ⚠ BOTH resources carry PANEL_VER in BOTH strings; CMakeLists.txt checks. */
type 'vers' {
    hex byte; hex byte; hex byte; hex byte; integer; pstring; pstring;
};
resource 'vers' (1) {
    0x01, 0x45, 0x80, 0x00,
    0,
    "1.4.8",
    "1.4.8 - AirPort Extreme status, on/off, choosing a network, forgetting one, and an About box"
};
resource 'vers' (2) {
    0x01, 0x45, 0x80, 0x00,
    0,
    "1.4.8",
    "1.4.8 - AirPort Extreme status, on/off, choosing a network, forgetting one, and an About box"
};

/* The "Choose network:" popup's menu (ap_panel.c kNetMenuID). One item, replaced at run time with the
 * network the driver is on; until then Apple's placeholder, an en dash. */
resource 'MENU' (200) {
    200, textMenuProc, allEnabled, enabled, "Network",
    {
        "\0xD0", noIcon, noKey, noMark, plain
    }
};

/* k211g: the passphrase dialog (ap_panel.c kNetPassDLOG = 300), matched to Apple's own "password prompt":
 * Apple's Note icon (ap_panel_note.r cicn 300, drawn in item 3's user item via PlotCIcon), Apple's exact
 * wording, a "Password:" label beside the field, and Cancel/Join. The field is bullet-masked by ApPassFilter
 * (the Dialog Manager has no masked EditText, so a ModalDialog filter keeps the real text and shows 0xA5
 * bullets). No help button, no "Add to Keychain" -- we store the PMK in the Preferences file (Keychain is a
 * possible future feature). Item 1 = Join (default), 2 = Cancel, 3 = the icon user item, 6 = the EditText
 * (the only editable item). The passphrase never leaves the panel: ap_panel.c derives the PMK, clears it. */
resource 'DITL' (300) {
    {
        {86, 278, 106, 348},  Button     { enabled, "Join" };
        {86, 196, 106, 266},  Button     { enabled, "Cancel" };
        {14, 16, 46, 48},     UserItem   { disabled };
        {12, 60, 48, 352},    StaticText { disabled, "The selected AirPort network requires a password to join." };
        {57, 56, 73, 126},    StaticText { disabled, "Password:" };
        {55, 130, 73, 352},   EditText   { enabled, "" };
    }
};

resource 'DLOG' (300) {
    {80, 80, 198, 444}, dBoxProc, invisible, noGoAway, 0x0, 300, "",
    centerParentWindowScreen
};

/* k211f: the Platinum look. The panel is an Appearance client (RegisterAppearanceClient), but a plain DLOG
 * still draws in the old black-and-white style unless a 'dlgx' with the theme flags accompanies it. Flags =
 * kDialogFlagsUseThemeBackground (1) | kDialogFlagsUseControlHierarchy (2) | kDialogFlagsUseThemeControls (8)
 * = 0x0B: the themed grey background and themed push buttons. Layout: version (int16)=0, flags (uint32). */
data 'dlgx' (300) {
    $"0000 0000 000B"
};

/* ---- Finder bundle. Owner 'APXp' -- the creator ../csm/ap_csm.c's "Open AirPort Extreme" looks for in
 * the Control Panels folder. kHasBundle and kHasCustomIcon are set after Rez by
 * ../csm/scripts/set-custom-icon.py.
 * ★ The icon is the user's "AirPort Extreme C Panel" family (ap_panel_icon.r, generated by
 * ../art/make-art.py and Rezzed as a second input), carried TWICE: at 128 for the bundle's ICN# entry
 * below (the desktop database, and the Application menu's small icon), and at -16455 with kHasCustomIcon,
 * which the Finder shows straight from the file. ⚠ The two must travel together: a BNDL naming a family the
 * file does not carry, or the custom-icon flag without one, renders a BLANK icon (the strip module's note). */
data 'APXp' (0) {
    "1.2, github.com/UnexpectedBomb"
};

/* FREF: file type 'APPL', local icon ID 0, empty name. */
data 'FREF' (128) {
    $"4150 504C 0000 00"
};

/* BNDL: owner 'APXp', owner ID 0, TWO types (count-1 = 1):
 *   'ICN#', one entry: local 0 -> ICN# 128 (the family in ap_panel_icon.r)
 *   'FREF', one entry: local 0 -> FREF 128 */
data 'BNDL' (128) {
    $"4150 5870 0000 0001"
    $"4943 4E23 0000 0000 0080"
    $"4652 4546 0000 0000 0080"
};
